Added user test inline command
weswigham/typescript-bot-test-triggerer pull request #5
Opened 2021-06-12 00:49 UTC by armanio123

Added new `@typescript-bot user test this inline` command.

2021-06-12 07:58 UTC, weswigham requested changes

2021-06-12 07:58 UTC, weswigham commented on GithubCommentReader/index.js
> +        branch: "master",
You'll probably need to swap this back~

2021-06-12 07:58 UTC, weswigham commented on GithubCommentReader/index.js
> +        }, `sync \`${branch}\` with master`);
This probably also needs to be swapped back to `main`?

2021-06-12 07:58 UTC, weswigham commented on GithubCommentReader/index.js
> +    .set(/user test this(?! slower|inline)/, action(async request => await makeNewBuildWithComments(request, "parallelized community code test suite", 33, async p => {
```suggestion
    .set(/user test this(?! slower| inline)/, action(async request => await makeNewBuildWithComments(request, "parallelized community code test suite", 33, async p => {

```
The whitespace in the regex has to be in both branches of the `|`.

2021-06-14 20:18 UTC, armanio123 commented on GithubCommentReader/index.js
> +        branch: "master",
Wow, I don't remember changing this. Fixed.

2021-06-14 20:20 UTC, armanio123 commented on GithubCommentReader/index.js
> +    .set(/user test this(?! slower|inline)/, action(async request => await makeNewBuildWithComments(request, "parallelized community code test suite", 33, async p => {
You're right. Fixed.

2021-06-14 20:20 UTC, armanio123 commented on GithubCommentReader/index.js
> +        }, `sync \`${branch}\` with master`);
Fixed.

2021-06-14 22:03 UTC, merged